import { render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { PerformanceWorkspace } from "@/components/analysis/performance-workspace";

const report = {
  source: "stored_artifacts", experiments_are_directly_comparable: false,
  message: { experiment: "experimental English SMS spam/ham baseline", evaluation_scope: "held_out_sms_test_split", accuracy: 0.9784431137724551, macro_f1: 0.9509784735812132, target_recall_label: "spam", target_recall: 0.8571428571428571, limitations: ["Does not establish performance on phishing, email, fraud, or modern messages."] },
  email: { experiment: "exploratory three-class email classification", evaluation_scope: "within_corpus_only", accuracy: 0.9536082474226805, macro_f1: 0.8855108990488052, target_recall_label: "Phishing", target_recall: 0.7611940298507462, limitations: ["Real-world generalization is not established."] },
  url: { experiment: "experimental URL-string-only phishing/benign classification", evaluation_scope: "filtered_official_temporal_test", accuracy: 0.9248621571948539, macro_f1: 0.9237103095823331, target_recall_label: "phish", target_recall: 0.8694570695560446, limitations: ["Domain overlap, collection-time confounding, and label noise limit generalization claims."] },
};
function response(body: unknown, status = 200): Response { return { ok: status < 400, status, json: vi.fn().mockResolvedValue(body) } as unknown as Response; }

describe("PerformanceWorkspace", () => {
  afterEach(() => vi.unstubAllGlobals());
  it("shows loading and the non-comparability disclosure", () => { vi.stubGlobal("fetch", vi.fn(() => new Promise(() => {}))); render(<PerformanceWorkspace/>); expect(screen.getByText(/Loading stored results/i)).toBeInTheDocument(); expect(screen.getByText(/not directly comparable/i)).toBeVisible(); });
  it("renders all experiments, exact returned metrics, human-readable scopes, and accessible meters", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(response(report))); render(<PerformanceWorkspace/>); await screen.findByRole("heading", { name: /Message \/ SMS spam/i }); expect(screen.getByRole("heading", { name: /Email three-class/i })).toBeInTheDocument(); expect(screen.getByRole("heading", { name: /URL phishing/i })).toBeInTheDocument(); expect(screen.getByText("0.9784")).toBeInTheDocument(); expect(screen.getByText("0.8855")).toBeInTheDocument(); expect(screen.getByText("0.8695")).toBeInTheDocument(); expect(screen.getAllByRole("meter")).toHaveLength(9); expect(screen.getAllByText("Within-corpus evaluation").length).toBeGreaterThan(0); expect(screen.getByText("within_corpus_only")).toBeInTheDocument(); });
  it("defines every exposed metric in plain language", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(response(report))); render(<PerformanceWorkspace/>); await screen.findByRole("heading", { name: "Metric definitions" }); expect(screen.getByText(/share of evaluated examples classified correctly/i)).toBeInTheDocument(); expect(screen.getByText(/giving each class equal weight/i)).toBeInTheDocument(); expect(screen.getByText(/named target class/i)).toBeInTheDocument(); });
  it("keeps task limitations visible and does not rank experiments", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(response(report))); render(<PerformanceWorkspace/>); await screen.findByText(/Ham means non-spam/i); expect(screen.getByText(/Real-world, source-independent/i)).toBeInTheDocument(); expect(screen.getByText(/No website content, redirects, DNS/i)).toBeInTheDocument(); expect(screen.getByText(/Metrics not exposed by this API/i)).toBeInTheDocument(); expect(screen.getByText(/not a leaderboard/i)).toBeInTheDocument(); expect(screen.queryByText(/best model|winner/i)).not.toBeInTheDocument(); });
  it("provides semantic experiment navigation", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(response(report))); render(<PerformanceWorkspace/>); const nav = await screen.findByRole("navigation", { name: /Performance experiments/i }); expect(nav).toContainElement(screen.getByRole("link", { name: /Message \/ SMS/i })); expect(screen.getByRole("link", { name: /Email/i })).toHaveAttribute("href", "#experiment-email"); });
  it("sanitizes unavailable and malformed API responses", async () => { vi.stubGlobal("fetch", vi.fn().mockRejectedValue(new Error("private detail"))); const first = render(<PerformanceWorkspace/>); const alert = await screen.findByRole("alert"); expect(alert).toHaveTextContent(/Performance results unavailable/i); expect(alert).not.toHaveTextContent(/private detail/i); first.unmount(); vi.stubGlobal("fetch", vi.fn().mockResolvedValue(response({ source: "stored_artifacts" }))); render(<PerformanceWorkspace/>); expect(await screen.findByRole("alert")).toHaveTextContent(/could not be loaded/i); });
});
