import { fireEvent, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { UrlWorkspace } from "@/components/analysis/url-workspace";

const base = { analysis_type: "url", prediction: "benign", classifier_outputs: { benign: .75, phish: .25 }, observed_indicators: [], disagreement: false, disagreement_message: null, verification_guidance: ["Verify through a trusted channel."], limitations: ["String only; never visits the website."] };
function response(body: unknown, status = 200): Response { return { ok: status < 400, status, json: vi.fn().mockResolvedValue(body) } as unknown as Response; }
function submit(value: string) { fireEvent.change(screen.getByLabelText(/Full URL/i), { target: { value } }); fireEvent.click(screen.getByRole("button", { name: "Analyze URL" })); }
describe("UrlWorkspace", () => {
  afterEach(() => vi.unstubAllGlobals());
  it("shows the no-fetch disclosure before analysis and validates empty input", () => { render(<UrlWorkspace/>); expect(screen.getByText(/does not visit the address/i)).toBeVisible(); expect(screen.getByText(/No website content, redirects, DNS, WHOIS/i)).toBeVisible(); expect(screen.getByText(/Enter a URL to analyze its string features/i)).toBeVisible(); fireEvent.click(screen.getByRole("button", { name: "Analyze URL" })); expect(screen.getByRole("alert")).toHaveTextContent(/Enter a URL/i); });
  it("renders benign output without a safety claim and keeps the submitted string non-clickable", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(response(base))); render(<UrlWorkspace/>); submit("https://non-routable.invalid/path"); await screen.findByRole("heading", { name: "Benign" }); expect(screen.getByText(/does not mean safe, verified, or trusted/i)).toBeInTheDocument(); expect(screen.getByText(/No supported URL-string indicators/i)).toBeInTheDocument(); expect(screen.queryByRole("link", { name: /non-routable/i })).not.toBeInTheDocument(); });
  it("renders phishing as non-definitive, observations separately, disagreement, and guidance", async () => { const value = { ...base, prediction: "phish", classifier_outputs: { benign: .1, phish: .9 }, observed_indicators: ["URL contains a userinfo (@) component"], verification_guidance: ["Do not open it."] }; vi.stubGlobal("fetch", vi.fn().mockResolvedValue(response(value))); render(<UrlWorkspace/>); submit("https://name@non-routable.invalid"); await screen.findByRole("heading", { name: "Phishing" }); expect(screen.getByText(/not proof/i)).toBeInTheDocument(); expect(screen.getByText(/userinfo/i)).toBeInTheDocument(); expect(screen.getByText("Do not open it.")).toBeInTheDocument(); });
  it("renders API disagreement and clears stale results when input changes", async () => { const value = { ...base, observed_indicators: ["URL specifies a non-default port"], disagreement: true, disagreement_message: "The classifier predicted Benign, but indicators warrant verification." }; vi.stubGlobal("fetch", vi.fn().mockResolvedValue(response(value))); render(<UrlWorkspace/>); submit("https://non-routable.invalid:8443"); await screen.findByText(/Signals do not fully agree/i); fireEvent.change(screen.getByLabelText(/Full URL/i), { target: { value: "https://changed.invalid" } }); expect(screen.queryByRole("heading", { name: "Benign" })).not.toBeInTheDocument(); });
  it("shows loading, server validation, and unavailable states", async () => { let resolve!: (value: Response) => void; vi.stubGlobal("fetch", vi.fn(() => new Promise<Response>((done) => { resolve = done; }))); render(<UrlWorkspace/>); submit("bad"); expect(screen.getAllByText(/Analyzing URL string/i).length).toBeGreaterThan(0); resolve(response({ detail: "URL must include an http:// or https:// scheme." }, 422)); expect(await screen.findByRole("alert")).toHaveTextContent(/http:\/\/ or https:\/\//i); });
  it("sanitizes an unavailable analysis service", async () => { vi.stubGlobal("fetch", vi.fn().mockRejectedValue(new Error("private transport detail"))); render(<UrlWorkspace/>); submit("https://non-routable.invalid"); const alert = await screen.findByRole("alert"); expect(alert).toHaveTextContent(/URL analysis unavailable/i); expect(alert).not.toHaveTextContent(/private transport detail/i); });
});
